version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 